# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  # theme_day: earth
  # theme_day: 1950s
  theme_day: nord
  #
  theme_night: nord
  # theme_night: mr_robot
  # theme_night: dark
  # theme_night: minimal
  #
  font: minimal 
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Jamie Y. Findlay personal academic website'
    twitter: 'findlayjy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''  
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true 
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

# footer:
#   copyright:
#     notice: '© {year} Me. This work is licensed under {license}'
#     license:
#       enable: true
#       allow_derivatives: false
#       share_alike: true
#       allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  # search:
  #   provider: wowchemy
  #   algolia:
  #     app_id: ''
  #     api_key: ''
  #     index_name: ''
  #     show_logo: false
  map:
    provider: 'google'
    api_key: 'AIzaSyAuD6uCApa8fV7aANwkyVKOMp0ZE9t0h0o'
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Publications
publications:
  date_format: January 2006
  citation_style: apa

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
